name: Run Python Action with Loguru

on: [push]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install loguru

      - name: Run Python script
        run: python action.py

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: action-logs
          path: action_log.log
