name: Capture Workflow Metadata

on:
  push:
    branches:
      - main

jobs:
  store-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Capture Workflow Metadata
        run: |
          mkdir -p logs
          echo "Workflow Run ID: $GITHUB_RUN_ID" > logs/metadata.log
          echo "Repository: $GITHUB_REPOSITORY" >> logs/metadata.log
          echo "Triggering Event: $GITHUB_EVENT_NAME" >> logs/metadata.log
          echo "Workflow Name: $GITHUB_WORKFLOW" >> logs/metadata.log
          echo "Job Name: $GITHUB_JOB" >> logs/metadata.log
          echo "Runner OS: $RUNNER_OS" >> logs/metadata.log
          echo "Run Attempt: $GITHUB_RUN_ATTEMPT" >> logs/metadata.log
          echo "Commit SHA: $GITHUB_SHA" >> logs/metadata.log
          echo "Branch: $GITHUB_REF_NAME" >> logs/metadata.log

      - name: Capture Workflow Logs
        run: |
          echo "Capturing GitHub Actions logs..."
          journalctl --user --no-pager --since "5 minutes ago" > logs/actions.log || true

      
