name: Multi-Action Logging

on: [push]

jobs:
  action-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Action One
        run: |
          echo "::group::Action One Logs"
          echo "Starting Action One"
          echo "Processing..."
          echo "Action One completed successfully."
          echo "::endgroup::"
      - name: Save logs
        run: |
          mkdir -p logs
          echo "Action One log content" > logs/action-one.log

  action-two:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Action Two
        run: |
          echo "::group::Action Two Logs"
          echo "Starting Action Two"
          echo "Performing tasks..."
          echo "Action Two completed."
          echo "::endgroup::"
      - name: Save logs
        run: |
          mkdir -p logs
          echo "Action Two log content" > logs/action-two.log

  upload-logs:
    needs: [action-one, action-two]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Upload Combined Logs
        uses: actions/upload-artifact@v4
        with:
          name: all-action-logs
          path: logs/
