name: Mayur

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project identifier'
        required: true
      verbosity:
        description: 'Logging verbosity level (info, debug, error)'
        required: false
        default: 'info'
  repository_dispatch:
    types: [trigger-instance]

env:
  LOG_BASE_DIR: logs

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      start-time: ${{ steps.start-time.outputs.time }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Capture start time
        id: start-time
        run: echo "time=$(date +%s)" >> "$GITHUB_OUTPUT"

  action-one:
    runs-on: ubuntu-latest
    needs: setup
    env:
      ACTION_LOG_DIR: "${{ env.LOG_BASE_DIR }}/action-one"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare logs directory for Action One
        run: mkdir -p "${{ env.ACTION_LOG_DIR }}"

      - name: Run Action One and log details
        id: action-one
        run: |
          {
            echo "--- Action One Log ---"
            echo "Project: ${{ github.event.inputs.project }}"
            echo "Run ID: ${{ github.run_id }}"
            echo "Action: action-one"
            echo "Status: Running"
            echo "Start Time: $(date)"
            echo "Processing Action One..."
            echo "End Time: $(date)"
            echo "Status: Completed"
          } | tee "${{ env.ACTION_LOG_DIR }}/action-one-details.log"
        continue-on-error: false

  finalize:
    runs-on: ubuntu-latest
    needs: [setup, action-one]
    env:
      FINAL_LOG_DIR: "${{ env.LOG_BASE_DIR }}/action-one"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifacts from Previous Jobs
        uses: actions/download-artifact@v4

      - name: Ensure action folder exists
        run: mkdir -p "${{ env.FINAL_LOG_DIR }}"

      - name: Capture end time and duration
        id: end-time
        run: |
          end_time=$(date +%s)
          start_time="${{ needs.setup.outputs.start-time }}"
          duration=$((end_time - start_time))
          {
            echo "Workflow Start Time: $(date -d @$start_time)"
            echo "Workflow End Time: $(date -d @$end_time)"
            echo "Total Duration: ${duration}s"
          } >> "${{ env.FINAL_LOG_DIR }}/action-one-details.log"

      - name: Append metadata to single log file
        run: |
          {
            echo "--- Metadata ---"
            echo "Project: ${{ github.event.inputs.project }}"
            echo "Run ID: ${{ github.run_id }}"
            echo "Status: ${{ job.status }}"
            echo "Triggered by: ${{ github.triggering_actor }}"
            echo "Verbosity Level: ${{ github.event.inputs.verbosity }}"
          } >> "${{ env.FINAL_LOG_DIR }}/action-one-details.log"

      - name: Upload Consolidated Log File
        uses: actions/upload-artifact@v4
        with:
          name: action-one-details
          path: "${{ env.FINAL_LOG_DIR }}/action-one-details.log"

      - name: Live Logging with Verbosity
        run: |
          if [ "${{ github.event.inputs.verbosity }}" = "debug" ]; then
            echo "--- Live Log Preview ---"
            cat "${{ env.FINAL_LOG_DIR }}/action-one-details.log"
          fi

  status-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch'
    steps:
      - name: Download Consolidated Log
        uses: actions/download-artifact@v4
        with:
          name: action-one-details

      - name: Display Instance Status
        run: |
          if [ -f "${{ env.LOG_BASE_DIR }}/action-one/action-one-details.log" ]; then
            echo "--- Retrieved Log Content ---"
            cat "${{ env.LOG_BASE_DIR }}/action-one/action-one-details.log"
          else
            echo "No log found for the provided Run ID."
          fi
